# http://about.travis-ci.org/docs/user/build-configuration/
language: ruby

#bundler_args: '--without production'

script: CODECLIMATE_REPO_TOKEN=7d6b988f58234bf1560305412d10d9530902beebdbe2fb938b6a934f1d352578 bundle exec rake

before_install:
  - "cat /etc/timezone"
  - "grep -i processor /proc/cpuinfo | wc -l"
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - "gem install bundler"
  - "bundle -v"

before_script:
  - "cp -f config/database.yml.example config/database.yml"
  - "cp -f config/application.yml.example config/application.yml"
  - "bundle exec rake db:drop db:create db:schema:load --trace 2>&1"

services:
    - postgresql

rvm:
  - 2.3.1
